### PR TITLE
Dns server tests

### PR DESCRIPTION
**Pull request by johntdyer**
```hcl
provider "thousandeyes" {
}

data "thousandeyes_agent" "hometest2" {
  name  = "hometest2"
}
resource "thousandeyes_dns_server" "dns_server_test" {
  name = "DNS Server Test"
  interval = 120

  dns_servers {
      server_name = "1.1.1.1"
  }
  domain = "google.com A"
  agents {
      agent_id = data.thousandeyes_agent.hometest2.agent_id
  }


}

output "thousandeyes_dns_server" {
  value = "${thousandeyes_dns_server.dns_server_test}"
}

```

```log
thousandeyes_dns_server = {
  "agents" = [
    {
      "agent_id" = 135711
    },
  ]
  "alert_rules" = []
  "alerts_enabled" = 1
  "bandwidth_measurements" = 1
  "bgp_measurements" = 1
  "bgp_monitors" = []
  "description" = ""
  "dns_servers" = [
    {
      "server_name" = "1.1.1.1"
    },
  ]
  "dns_transport_protocol" = "UDP"
  "domain" = "google.com A"
  "enabled" = 1
  "id" = "1300655"
  "interval" = 120
  "mtu_measurements" = 1
  "name" = "DNS Server Test"
  "network_measurements" = 1
  "num_path_traces" = 3
  "path_trace_mode" = "classic"
  "probe_mode" = "AUTO"
  "protocol" = "TCP"
  "recursive_queries" = 1
}
```

### CODE REVIEW

**Comment by johntdyer** [comment]
i really am unsure why all those commits are showing up in these branches... I am trying to keep things sane on my end by creating feature branch, pushing, PR and on my end I'm merging that feature branch back into my local master... Perhaps thats where the problem is.. I am just usure how else to do it since my work is often dependent on earlier commits ...

**Comment by william20111** [comment]
> i really am unsure why all those commits are showing up in these branches... I am trying to keep things sane on my end by creating feature branch, pushing, PR and on my end I'm merging that feature branch back into my local master... Perhaps thats where the problem is.. I am just usure how else to do it since my work is often dependent on earlier commits ...

Hmm not sure lots of commits on the branch. If resolve the conflicts will look to merge this one

**Comment by johntdyer** [comment]
@william20111  Lets wait until the other two PR's are good and then I can handle these conflicts...

**Comment by johntdyer** [comment]
@william20111  think we're good here too

**Pull request merged**
